//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HuertaDirectaEntities : DbContext
    {
        public HuertaDirectaEntities()
            : base("name=HuertaDirectaEntities")
        {
        }

        public HuertaDirectaEntities(string nameOrConnectionString) : base(nameOrConnectionString)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<barrioGuardar_Result> barrioGuardar(Nullable<int> id, Nullable<int> idCiudad, string nombre)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var idCiudadParameter = idCiudad.HasValue ?
                new ObjectParameter("idCiudad", idCiudad) :
                new ObjectParameter("idCiudad", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<barrioGuardar_Result>("barrioGuardar", idParameter, idCiudadParameter, nombreParameter);
        }
    
        public virtual ObjectResult<barrioLeer_Result> barrioLeer(Nullable<int> id, Nullable<int> idCiudad, string nombre)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var idCiudadParameter = idCiudad.HasValue ?
                new ObjectParameter("idCiudad", idCiudad) :
                new ObjectParameter("idCiudad", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<barrioLeer_Result>("barrioLeer", idParameter, idCiudadParameter, nombreParameter);
        }
    
        public virtual ObjectResult<calleGuardar_Result> calleGuardar(Nullable<int> id, Nullable<int> idCiudad, string nombre)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var idCiudadParameter = idCiudad.HasValue ?
                new ObjectParameter("idCiudad", idCiudad) :
                new ObjectParameter("idCiudad", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<calleGuardar_Result>("calleGuardar", idParameter, idCiudadParameter, nombreParameter);
        }
    
        public virtual ObjectResult<calleLeer_Result> calleLeer(Nullable<int> id, Nullable<int> idCiudad, string nombre)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var idCiudadParameter = idCiudad.HasValue ?
                new ObjectParameter("idCiudad", idCiudad) :
                new ObjectParameter("idCiudad", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<calleLeer_Result>("calleLeer", idParameter, idCiudadParameter, nombreParameter);
        }
    
        public virtual ObjectResult<categoriaGuardar_Result> categoriaGuardar(Nullable<int> id, string nombre)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<categoriaGuardar_Result>("categoriaGuardar", idParameter, nombreParameter);
        }
    
        public virtual ObjectResult<categoriaLeer_Result> categoriaLeer(Nullable<int> id, string nombre)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<categoriaLeer_Result>("categoriaLeer", idParameter, nombreParameter);
        }
    
        public virtual ObjectResult<ciudadGuardar_Result> ciudadGuardar(Nullable<int> id, Nullable<int> idLocalidad, string nombre)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var idLocalidadParameter = idLocalidad.HasValue ?
                new ObjectParameter("idLocalidad", idLocalidad) :
                new ObjectParameter("idLocalidad", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ciudadGuardar_Result>("ciudadGuardar", idParameter, idLocalidadParameter, nombreParameter);
        }
    
        public virtual ObjectResult<ciudadLeer_Result> ciudadLeer(Nullable<int> id, Nullable<int> idLocalidad, string nombre)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var idLocalidadParameter = idLocalidad.HasValue ?
                new ObjectParameter("idLocalidad", idLocalidad) :
                new ObjectParameter("idLocalidad", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ciudadLeer_Result>("ciudadLeer", idParameter, idLocalidadParameter, nombreParameter);
        }
    
        public virtual ObjectResult<direccionGuardar_Result> direccionGuardar(Nullable<int> id, Nullable<int> latitud, Nullable<int> longitud, string manzana, string solar, string apto, string numero, Nullable<int> codigoCalle, Nullable<int> codigoCalleEsquina, Nullable<int> localidad, Nullable<int> codigoCiudad, Nullable<int> codigoProvincia, Nullable<int> codigoPais)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var latitudParameter = latitud.HasValue ?
                new ObjectParameter("latitud", latitud) :
                new ObjectParameter("latitud", typeof(int));
    
            var longitudParameter = longitud.HasValue ?
                new ObjectParameter("longitud", longitud) :
                new ObjectParameter("longitud", typeof(int));
    
            var manzanaParameter = manzana != null ?
                new ObjectParameter("manzana", manzana) :
                new ObjectParameter("manzana", typeof(string));
    
            var solarParameter = solar != null ?
                new ObjectParameter("solar", solar) :
                new ObjectParameter("solar", typeof(string));
    
            var aptoParameter = apto != null ?
                new ObjectParameter("apto", apto) :
                new ObjectParameter("apto", typeof(string));
    
            var numeroParameter = numero != null ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(string));
    
            var codigoCalleParameter = codigoCalle.HasValue ?
                new ObjectParameter("codigoCalle", codigoCalle) :
                new ObjectParameter("codigoCalle", typeof(int));
    
            var codigoCalleEsquinaParameter = codigoCalleEsquina.HasValue ?
                new ObjectParameter("codigoCalleEsquina", codigoCalleEsquina) :
                new ObjectParameter("codigoCalleEsquina", typeof(int));
    
            var localidadParameter = localidad.HasValue ?
                new ObjectParameter("localidad", localidad) :
                new ObjectParameter("localidad", typeof(int));
    
            var codigoCiudadParameter = codigoCiudad.HasValue ?
                new ObjectParameter("codigoCiudad", codigoCiudad) :
                new ObjectParameter("codigoCiudad", typeof(int));
    
            var codigoProvinciaParameter = codigoProvincia.HasValue ?
                new ObjectParameter("codigoProvincia", codigoProvincia) :
                new ObjectParameter("codigoProvincia", typeof(int));
    
            var codigoPaisParameter = codigoPais.HasValue ?
                new ObjectParameter("codigoPais", codigoPais) :
                new ObjectParameter("codigoPais", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<direccionGuardar_Result>("direccionGuardar", idParameter, latitudParameter, longitudParameter, manzanaParameter, solarParameter, aptoParameter, numeroParameter, codigoCalleParameter, codigoCalleEsquinaParameter, localidadParameter, codigoCiudadParameter, codigoProvinciaParameter, codigoPaisParameter);
        }
    
        public virtual ObjectResult<direccionLeer_Result> direccionLeer(Nullable<int> id, Nullable<int> latitud, Nullable<int> longitud, string manzana, string solar, string apto, string numero, Nullable<int> codigoCalle, Nullable<int> codigoCalleEsquina, Nullable<int> localidad, Nullable<int> codigoCiudad, Nullable<int> codigoProvincia, Nullable<int> codigoPais)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var latitudParameter = latitud.HasValue ?
                new ObjectParameter("latitud", latitud) :
                new ObjectParameter("latitud", typeof(int));
    
            var longitudParameter = longitud.HasValue ?
                new ObjectParameter("longitud", longitud) :
                new ObjectParameter("longitud", typeof(int));
    
            var manzanaParameter = manzana != null ?
                new ObjectParameter("manzana", manzana) :
                new ObjectParameter("manzana", typeof(string));
    
            var solarParameter = solar != null ?
                new ObjectParameter("solar", solar) :
                new ObjectParameter("solar", typeof(string));
    
            var aptoParameter = apto != null ?
                new ObjectParameter("apto", apto) :
                new ObjectParameter("apto", typeof(string));
    
            var numeroParameter = numero != null ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(string));
    
            var codigoCalleParameter = codigoCalle.HasValue ?
                new ObjectParameter("codigoCalle", codigoCalle) :
                new ObjectParameter("codigoCalle", typeof(int));
    
            var codigoCalleEsquinaParameter = codigoCalleEsquina.HasValue ?
                new ObjectParameter("codigoCalleEsquina", codigoCalleEsquina) :
                new ObjectParameter("codigoCalleEsquina", typeof(int));
    
            var localidadParameter = localidad.HasValue ?
                new ObjectParameter("localidad", localidad) :
                new ObjectParameter("localidad", typeof(int));
    
            var codigoCiudadParameter = codigoCiudad.HasValue ?
                new ObjectParameter("codigoCiudad", codigoCiudad) :
                new ObjectParameter("codigoCiudad", typeof(int));
    
            var codigoProvinciaParameter = codigoProvincia.HasValue ?
                new ObjectParameter("codigoProvincia", codigoProvincia) :
                new ObjectParameter("codigoProvincia", typeof(int));
    
            var codigoPaisParameter = codigoPais.HasValue ?
                new ObjectParameter("codigoPais", codigoPais) :
                new ObjectParameter("codigoPais", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<direccionLeer_Result>("direccionLeer", idParameter, latitudParameter, longitudParameter, manzanaParameter, solarParameter, aptoParameter, numeroParameter, codigoCalleParameter, codigoCalleEsquinaParameter, localidadParameter, codigoCiudadParameter, codigoProvinciaParameter, codigoPaisParameter);
        }
    
        public virtual ObjectResult<imagenGuardar_Result> imagenGuardar(Nullable<int> id, string imagen)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("imagen", imagen) :
                new ObjectParameter("imagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<imagenGuardar_Result>("imagenGuardar", idParameter, imagenParameter);
        }
    
        public virtual ObjectResult<imagenLeer_Result> imagenLeer(Nullable<int> id, string imagen)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("imagen", imagen) :
                new ObjectParameter("imagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<imagenLeer_Result>("imagenLeer", idParameter, imagenParameter);
        }
    
        public virtual ObjectResult<monedaGuardar_Result> monedaGuardar(Nullable<int> id, string nombre)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<monedaGuardar_Result>("monedaGuardar", idParameter, nombreParameter);
        }
    
        public virtual ObjectResult<monedaLeer_Result> monedaLeer(Nullable<int> id, string nombre)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<monedaLeer_Result>("monedaLeer", idParameter, nombreParameter);
        }
    
        public virtual ObjectResult<PaisGuardar_Result> PaisGuardar(Nullable<int> id, string nombre)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PaisGuardar_Result>("PaisGuardar", idParameter, nombreParameter);
        }
    
        public virtual ObjectResult<PaisLeer_Result> PaisLeer(Nullable<int> id, string nombre)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PaisLeer_Result>("PaisLeer", idParameter, nombreParameter);
        }
    
        public virtual ObjectResult<pedidoDetalleGuardar_Result> pedidoDetalleGuardar(Nullable<int> idPedido, Nullable<int> idItem, Nullable<int> idProducto, Nullable<int> idProductor)
        {
            var idPedidoParameter = idPedido.HasValue ?
                new ObjectParameter("idPedido", idPedido) :
                new ObjectParameter("idPedido", typeof(int));
    
            var idItemParameter = idItem.HasValue ?
                new ObjectParameter("idItem", idItem) :
                new ObjectParameter("idItem", typeof(int));
    
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("idProducto", idProducto) :
                new ObjectParameter("idProducto", typeof(int));
    
            var idProductorParameter = idProductor.HasValue ?
                new ObjectParameter("idProductor", idProductor) :
                new ObjectParameter("idProductor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pedidoDetalleGuardar_Result>("pedidoDetalleGuardar", idPedidoParameter, idItemParameter, idProductoParameter, idProductorParameter);
        }
    
        public virtual ObjectResult<pedidoDetalleLeer_Result> pedidoDetalleLeer(Nullable<int> idPedido, Nullable<int> idItem, Nullable<int> idProducto, Nullable<int> idProductor)
        {
            var idPedidoParameter = idPedido.HasValue ?
                new ObjectParameter("idPedido", idPedido) :
                new ObjectParameter("idPedido", typeof(int));
    
            var idItemParameter = idItem.HasValue ?
                new ObjectParameter("idItem", idItem) :
                new ObjectParameter("idItem", typeof(int));
    
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("idProducto", idProducto) :
                new ObjectParameter("idProducto", typeof(int));
    
            var idProductorParameter = idProductor.HasValue ?
                new ObjectParameter("idProductor", idProductor) :
                new ObjectParameter("idProductor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pedidoDetalleLeer_Result>("pedidoDetalleLeer", idPedidoParameter, idItemParameter, idProductoParameter, idProductorParameter);
        }
    
        public virtual ObjectResult<pedidoGuardar_Result> pedidoGuardar(Nullable<int> id, Nullable<int> idPersonaDestinatario, Nullable<int> moneda, Nullable<decimal> monto, Nullable<int> estado)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var idPersonaDestinatarioParameter = idPersonaDestinatario.HasValue ?
                new ObjectParameter("idPersonaDestinatario", idPersonaDestinatario) :
                new ObjectParameter("idPersonaDestinatario", typeof(int));
    
            var monedaParameter = moneda.HasValue ?
                new ObjectParameter("moneda", moneda) :
                new ObjectParameter("moneda", typeof(int));
    
            var montoParameter = monto.HasValue ?
                new ObjectParameter("monto", monto) :
                new ObjectParameter("monto", typeof(decimal));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pedidoGuardar_Result>("pedidoGuardar", idParameter, idPersonaDestinatarioParameter, monedaParameter, montoParameter, estadoParameter);
        }
    
        public virtual ObjectResult<pedidoLeer_Result> pedidoLeer(Nullable<int> id, Nullable<int> idPersonaDestinatario, Nullable<int> moneda, Nullable<decimal> monto, Nullable<int> estado)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var idPersonaDestinatarioParameter = idPersonaDestinatario.HasValue ?
                new ObjectParameter("idPersonaDestinatario", idPersonaDestinatario) :
                new ObjectParameter("idPersonaDestinatario", typeof(int));
    
            var monedaParameter = moneda.HasValue ?
                new ObjectParameter("moneda", moneda) :
                new ObjectParameter("moneda", typeof(int));
    
            var montoParameter = monto.HasValue ?
                new ObjectParameter("monto", monto) :
                new ObjectParameter("monto", typeof(decimal));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pedidoLeer_Result>("pedidoLeer", idParameter, idPersonaDestinatarioParameter, monedaParameter, montoParameter, estadoParameter);
        }
    
        public virtual ObjectResult<PersonaGuardar_Result> PersonaGuardar(Nullable<int> id, string primerNombre, string segundoNombre, string primerApellido, string segundoApellido, Nullable<int> tipoDocumento, string numeroDocumento, string email, string telefonoFijo, string telefonoMovil, Nullable<System.DateTime> fechaAlta, Nullable<System.DateTime> fechaBaja, Nullable<int> estado, Nullable<int> calificacion)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var primerNombreParameter = primerNombre != null ?
                new ObjectParameter("primerNombre", primerNombre) :
                new ObjectParameter("primerNombre", typeof(string));
    
            var segundoNombreParameter = segundoNombre != null ?
                new ObjectParameter("segundoNombre", segundoNombre) :
                new ObjectParameter("segundoNombre", typeof(string));
    
            var primerApellidoParameter = primerApellido != null ?
                new ObjectParameter("primerApellido", primerApellido) :
                new ObjectParameter("primerApellido", typeof(string));
    
            var segundoApellidoParameter = segundoApellido != null ?
                new ObjectParameter("segundoApellido", segundoApellido) :
                new ObjectParameter("segundoApellido", typeof(string));
    
            var tipoDocumentoParameter = tipoDocumento.HasValue ?
                new ObjectParameter("tipoDocumento", tipoDocumento) :
                new ObjectParameter("tipoDocumento", typeof(int));
    
            var numeroDocumentoParameter = numeroDocumento != null ?
                new ObjectParameter("numeroDocumento", numeroDocumento) :
                new ObjectParameter("numeroDocumento", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var telefonoFijoParameter = telefonoFijo != null ?
                new ObjectParameter("telefonoFijo", telefonoFijo) :
                new ObjectParameter("telefonoFijo", typeof(string));
    
            var telefonoMovilParameter = telefonoMovil != null ?
                new ObjectParameter("telefonoMovil", telefonoMovil) :
                new ObjectParameter("telefonoMovil", typeof(string));
    
            var fechaAltaParameter = fechaAlta.HasValue ?
                new ObjectParameter("fechaAlta", fechaAlta) :
                new ObjectParameter("fechaAlta", typeof(System.DateTime));
    
            var fechaBajaParameter = fechaBaja.HasValue ?
                new ObjectParameter("fechaBaja", fechaBaja) :
                new ObjectParameter("fechaBaja", typeof(System.DateTime));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(int));
    
            var calificacionParameter = calificacion.HasValue ?
                new ObjectParameter("calificacion", calificacion) :
                new ObjectParameter("calificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PersonaGuardar_Result>("PersonaGuardar", idParameter, primerNombreParameter, segundoNombreParameter, primerApellidoParameter, segundoApellidoParameter, tipoDocumentoParameter, numeroDocumentoParameter, emailParameter, telefonoFijoParameter, telefonoMovilParameter, fechaAltaParameter, fechaBajaParameter, estadoParameter, calificacionParameter);
        }
    
        public virtual ObjectResult<PersonaLeer_Result> PersonaLeer(Nullable<int> id, string primerNombre, string segundoNombre, string primerApellido, string segundoApellido, Nullable<int> tipoDocumento, string numeroDocumento, string email, string telefonoFijo, string telefonoMovil, Nullable<System.DateTime> fechaAlta, Nullable<System.DateTime> fechaBaja, Nullable<int> estado, Nullable<int> calificacion)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var primerNombreParameter = primerNombre != null ?
                new ObjectParameter("primerNombre", primerNombre) :
                new ObjectParameter("primerNombre", typeof(string));
    
            var segundoNombreParameter = segundoNombre != null ?
                new ObjectParameter("segundoNombre", segundoNombre) :
                new ObjectParameter("segundoNombre", typeof(string));
    
            var primerApellidoParameter = primerApellido != null ?
                new ObjectParameter("primerApellido", primerApellido) :
                new ObjectParameter("primerApellido", typeof(string));
    
            var segundoApellidoParameter = segundoApellido != null ?
                new ObjectParameter("segundoApellido", segundoApellido) :
                new ObjectParameter("segundoApellido", typeof(string));
    
            var tipoDocumentoParameter = tipoDocumento.HasValue ?
                new ObjectParameter("tipoDocumento", tipoDocumento) :
                new ObjectParameter("tipoDocumento", typeof(int));
    
            var numeroDocumentoParameter = numeroDocumento != null ?
                new ObjectParameter("numeroDocumento", numeroDocumento) :
                new ObjectParameter("numeroDocumento", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var telefonoFijoParameter = telefonoFijo != null ?
                new ObjectParameter("telefonoFijo", telefonoFijo) :
                new ObjectParameter("telefonoFijo", typeof(string));
    
            var telefonoMovilParameter = telefonoMovil != null ?
                new ObjectParameter("telefonoMovil", telefonoMovil) :
                new ObjectParameter("telefonoMovil", typeof(string));
    
            var fechaAltaParameter = fechaAlta.HasValue ?
                new ObjectParameter("fechaAlta", fechaAlta) :
                new ObjectParameter("fechaAlta", typeof(System.DateTime));
    
            var fechaBajaParameter = fechaBaja.HasValue ?
                new ObjectParameter("fechaBaja", fechaBaja) :
                new ObjectParameter("fechaBaja", typeof(System.DateTime));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(int));
    
            var calificacionParameter = calificacion.HasValue ?
                new ObjectParameter("calificacion", calificacion) :
                new ObjectParameter("calificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PersonaLeer_Result>("PersonaLeer", idParameter, primerNombreParameter, segundoNombreParameter, primerApellidoParameter, segundoApellidoParameter, tipoDocumentoParameter, numeroDocumentoParameter, emailParameter, telefonoFijoParameter, telefonoMovilParameter, fechaAltaParameter, fechaBajaParameter, estadoParameter, calificacionParameter);
        }
    
        public virtual ObjectResult<productoGuardar_Result> productoGuardar(Nullable<int> id, Nullable<int> idCategoria, string nombre, string descripcion)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var idCategoriaParameter = idCategoria.HasValue ?
                new ObjectParameter("idCategoria", idCategoria) :
                new ObjectParameter("idCategoria", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<productoGuardar_Result>("productoGuardar", idParameter, idCategoriaParameter, nombreParameter, descripcionParameter);
        }
    
        public virtual ObjectResult<productoLeer_Result> productoLeer(Nullable<int> id, Nullable<int> idCategoria, string nombre, string descripcion)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var idCategoriaParameter = idCategoria.HasValue ?
                new ObjectParameter("idCategoria", idCategoria) :
                new ObjectParameter("idCategoria", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<productoLeer_Result>("productoLeer", idParameter, idCategoriaParameter, nombreParameter, descripcionParameter);
        }
    
        public virtual ObjectResult<productoProductorGuardar_Result> productoProductorGuardar(Nullable<int> idProducto, Nullable<int> idProductor, string descripcion, Nullable<int> codigoMoneda, Nullable<decimal> precio, Nullable<int> codigoTipoUnidad, string linkSitio, string linkRedSocial)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("idProducto", idProducto) :
                new ObjectParameter("idProducto", typeof(int));
    
            var idProductorParameter = idProductor.HasValue ?
                new ObjectParameter("idProductor", idProductor) :
                new ObjectParameter("idProductor", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var codigoMonedaParameter = codigoMoneda.HasValue ?
                new ObjectParameter("codigoMoneda", codigoMoneda) :
                new ObjectParameter("codigoMoneda", typeof(int));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(decimal));
    
            var codigoTipoUnidadParameter = codigoTipoUnidad.HasValue ?
                new ObjectParameter("codigoTipoUnidad", codigoTipoUnidad) :
                new ObjectParameter("codigoTipoUnidad", typeof(int));
    
            var linkSitioParameter = linkSitio != null ?
                new ObjectParameter("linkSitio", linkSitio) :
                new ObjectParameter("linkSitio", typeof(string));
    
            var linkRedSocialParameter = linkRedSocial != null ?
                new ObjectParameter("linkRedSocial", linkRedSocial) :
                new ObjectParameter("linkRedSocial", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<productoProductorGuardar_Result>("productoProductorGuardar", idProductoParameter, idProductorParameter, descripcionParameter, codigoMonedaParameter, precioParameter, codigoTipoUnidadParameter, linkSitioParameter, linkRedSocialParameter);
        }
    
        public virtual ObjectResult<productoProductorLeer_Result> productoProductorLeer(Nullable<int> idProducto, Nullable<int> idProductor, string descripcion, Nullable<int> codigoMoneda, Nullable<decimal> precio, Nullable<int> codigoTipoUnidad, string linkSitio, string linkRedSocial)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("idProducto", idProducto) :
                new ObjectParameter("idProducto", typeof(int));
    
            var idProductorParameter = idProductor.HasValue ?
                new ObjectParameter("idProductor", idProductor) :
                new ObjectParameter("idProductor", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var codigoMonedaParameter = codigoMoneda.HasValue ?
                new ObjectParameter("codigoMoneda", codigoMoneda) :
                new ObjectParameter("codigoMoneda", typeof(int));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(decimal));
    
            var codigoTipoUnidadParameter = codigoTipoUnidad.HasValue ?
                new ObjectParameter("codigoTipoUnidad", codigoTipoUnidad) :
                new ObjectParameter("codigoTipoUnidad", typeof(int));
    
            var linkSitioParameter = linkSitio != null ?
                new ObjectParameter("linkSitio", linkSitio) :
                new ObjectParameter("linkSitio", typeof(string));
    
            var linkRedSocialParameter = linkRedSocial != null ?
                new ObjectParameter("linkRedSocial", linkRedSocial) :
                new ObjectParameter("linkRedSocial", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<productoProductorLeer_Result>("productoProductorLeer", idProductoParameter, idProductorParameter, descripcionParameter, codigoMonedaParameter, precioParameter, codigoTipoUnidadParameter, linkSitioParameter, linkRedSocialParameter);
        }
    
        public virtual ObjectResult<productorGuardar_Result> productorGuardar(Nullable<int> id, Nullable<int> idPersona, string nombreFantasia, string descripcion)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var idPersonaParameter = idPersona.HasValue ?
                new ObjectParameter("idPersona", idPersona) :
                new ObjectParameter("idPersona", typeof(int));
    
            var nombreFantasiaParameter = nombreFantasia != null ?
                new ObjectParameter("nombreFantasia", nombreFantasia) :
                new ObjectParameter("nombreFantasia", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<productorGuardar_Result>("productorGuardar", idParameter, idPersonaParameter, nombreFantasiaParameter, descripcionParameter);
        }
    
        public virtual ObjectResult<productorLeer_Result> productorLeer(Nullable<int> id, Nullable<int> idPersona, string nombreFantasia, string descripcion)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var idPersonaParameter = idPersona.HasValue ?
                new ObjectParameter("idPersona", idPersona) :
                new ObjectParameter("idPersona", typeof(int));
    
            var nombreFantasiaParameter = nombreFantasia != null ?
                new ObjectParameter("nombreFantasia", nombreFantasia) :
                new ObjectParameter("nombreFantasia", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<productorLeer_Result>("productorLeer", idParameter, idPersonaParameter, nombreFantasiaParameter, descripcionParameter);
        }
    
        public virtual ObjectResult<provinciaGuardar_Result> provinciaGuardar(Nullable<int> id, Nullable<int> idPais, string nombre)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var idPaisParameter = idPais.HasValue ?
                new ObjectParameter("idPais", idPais) :
                new ObjectParameter("idPais", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<provinciaGuardar_Result>("provinciaGuardar", idParameter, idPaisParameter, nombreParameter);
        }
    
        public virtual ObjectResult<provinciaLeer_Result> provinciaLeer(Nullable<int> id, Nullable<int> idPais, string nombre)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var idPaisParameter = idPais.HasValue ?
                new ObjectParameter("idPais", idPais) :
                new ObjectParameter("idPais", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<provinciaLeer_Result>("provinciaLeer", idParameter, idPaisParameter, nombreParameter);
        }
    
        public virtual ObjectResult<tipoUnidadGuardar_Result> tipoUnidadGuardar(Nullable<int> id, string nombre)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tipoUnidadGuardar_Result>("tipoUnidadGuardar", idParameter, nombreParameter);
        }
    
        public virtual ObjectResult<tipoUnidadLeer_Result> tipoUnidadLeer(Nullable<int> id, string nombre)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tipoUnidadLeer_Result>("tipoUnidadLeer", idParameter, nombreParameter);
        }
    
        public virtual ObjectResult<UsuarioGuardar_Result> UsuarioGuardar(string usuario, string password, Nullable<System.DateTime> fechaAlta, Nullable<int> estado)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var fechaAltaParameter = fechaAlta.HasValue ?
                new ObjectParameter("fechaAlta", fechaAlta) :
                new ObjectParameter("fechaAlta", typeof(System.DateTime));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsuarioGuardar_Result>("UsuarioGuardar", usuarioParameter, passwordParameter, fechaAltaParameter, estadoParameter);
        }
    
        public virtual ObjectResult<UsuarioLeer_Result> UsuarioLeer(string usuario, string password, Nullable<System.DateTime> fechaAlta, Nullable<int> estado)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var fechaAltaParameter = fechaAlta.HasValue ?
                new ObjectParameter("fechaAlta", fechaAlta) :
                new ObjectParameter("fechaAlta", typeof(System.DateTime));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsuarioLeer_Result>("UsuarioLeer", usuarioParameter, passwordParameter, fechaAltaParameter, estadoParameter);
        }
    
        public virtual ObjectResult<login_Result> login(string usuario, string password)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<login_Result>("login", usuarioParameter, passwordParameter);
        }
    }
}
